### PR TITLE
Stablizes transforms of class property arrow functions

### LINKED ISSUE #134: Migration result in broken code for class members
Hello! Thanks for this super helpful package. I've come across a pattern that unfortunately results in _more_ errors which then makes the script run longer than necessary because there are more errors.

It seems that the error is that a replace isn't working properly and it's adding duplicate nodes instead. I've included the smallest reproducible case I could figure out below. It seems too have something to do with the single line class property (the issue goes away if I make the arrow function multi-lined with `{ ... }`).

Looking at debug steps from other issues I tried commenting out other plugins in `cli.js`, and I've narrowed it down to `add-conversions`. I was picking around in that file for a while, but haven't yet found the cause.

I will keep looking for the fix and am glad to put up a PR, but I figured it would create this issue to maybe shortcut that process.

If I cannot find a solution, a workaround for my process seems to be to first run a mod to change class property implicit return arrow functions into ones with explicit returns. I have not fully tested this yet.

___

**Before conversion**
```typescript
class Foo {
  constructor() {
    this.foo = "";
  }

  getFoo = () => this.foo;
}

```

**After migration**
```typescript
class Foo {
    constructor() {
        // @ts-expect-error ts-migrate(2339) FIXME: Property 'foo' does not exist on type 'Foo'.
        this.foo = "";
    }
    getFoo = () => (this as $TSFixMe).foo;
}
    (this as $TSFixMe).foo = "";
  }

  // @ts-expect-error ts-migrate(2304) FIXME: Cannot find name 'getFoo'.
  getFoo = () => this.foo;
}

```

**tsconfig.json**
```json
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "noEmit": true,
    "strict": true 
  },
  "include": ["src"],
  "exclude": ["node_modules/**/*"]
}

```

### PR DESCRIPTION
**Pull request by sfrieson**
Closes #134, an issue I ran into when trying to migrate multiple repos that resulted in broken code in certain files.

I am not entirely sure if this is the best way to make the fix, so any pointers there would be appreciated. The fix is working for a minimal test case (in the test suite) as well as on my code base leaving the syntax in place and removing 15 of 392 `@ts-expect-error`s.

I have seen cases where white space can get messed up as mentioned in the comment for `shouldReplace`.

Willing to work towards a different solution is there is a better one.

### CODE REVIEW

**Comment by edsrzf** [comment]
Thanks, I think this looks like a promising fix. I will take a closer look over the weekend. I've also found another issue or two I introduced in #127 that I will aim to fix.

**Comment by pmusiala** [comment]
Is it possible to merge it anytime soon?

**Review by Rudeg — APPROVED** [review]
